### ISSUE TITLE
TypeError: self.currentProvider.sendAsync is not a function

### ISSUE THREAD

**Issue by miguelmota** [ethjs/ethjs#6]
Getting error when calling a contract instance method when using websocket provider 

```
TypeError: self.currentProvider.sendAsync is not a function
```

**Comment by SilentCicero** [comment]
Can you provide more context for this issue, apologies for the late reply.

**Comment by miguelmota** [comment]
Error occurs when using a websocket provider, e.g `new Web3.providers.WebsocketProvider('wss://rinkeby.infura.io/ws')` and then attempting to call a contract method

<img width="378" alt="screen shot 2017-11-07 at 11 17 05 am" src="https://user-images.githubusercontent.com/168240/32512875-47d0619a-c3ad-11e7-89b7-f1375820f71f.png">

**Comment by miguelmota** [comment]
I think it's a Web3 issue. More information in this web3 issue thread https://github.com/ethereum/web3.js/issues/1119

Workaround is to do

```
Web3.providers.HttpProvider.prototype.sendAsync = Web3.providers.HttpProvider.prototype.send
```

**Comment by Shrugs** [comment]
Just commenting for anyone else that stumbles into this error via google.

This is caused because the connection to your ws isn't open. So it likely won't be an issue with web3 and similar. This is an issue with your connection. In my case, I forgot to expose the websocket port in my docker container. For super open websocket permissions, run (geth) `--ws --wsport 8546 --wsaddr "0.0.0.0" --wsorigins="*" \`

**Comment by SilentCicero** [comment]
I have not tested the web socket provider, and I believe it has a different API. I could be wrong though.

**Comment by ryu9827** [comment]
what I did is, I changed `web3.currentProvider.sendAsync` to `web3.currentProvider.send`, and it works fine.
